name: Run tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install dataframe libraries
      run: |
        pip install ray git+https://github.com/modin-project/modin
        pip install vaex  # use stable as no nightly builds and long build time
        pip install pandas --no-deps --ignore-installed  # use stable as erroneous nightly builds and long build time
    - name: Run tests
      run: |
        pytest tests/ -v --ci
