name: Run tests
on:
  push: null
  schedule:
    - cron: '0 0 * * 0'  # i.e. every week
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Upgrade pip
      run: |
        pip install pip --upgrade
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install dataframe libraries
      run: |
        pip install ray git+https://github.com/modin-project/modin
        pip install vaex  # use stable as no nightly builds and long build time
        pip install --pre --extra-index https://pypi.anaconda.org/scipy-wheels-nightly/simple pandas --ignore-installed --no-deps
    - name: Run tests
      run: |
        pytest tests/ -v --ci
